version: '3'

services:
  battle-stream:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: battle-memecoin-stream
    restart: unless-stopped
    volumes:
      - ./logs:/home/streamer/game/logs
      # Uncomment to mount your stream keys file
      # - ./stream-keys.json:/home/streamer/game/stream-keys.json
    ports:
      - "8080:8080"
    environment:
      - YOUTUBE_STREAM_KEY=${YOUTUBE_STREAM_KEY:-}
      - TWITCH_STREAM_KEY=${TWITCH_STREAM_KEY:-}
      - FACEBOOK_STREAM_KEY=${FACEBOOK_STREAM_KEY:-}
    # Uncomment to use host network (better performance for streaming)
    # network_mode: "host"
    # If using host network, comment out the ports section above

  # Optional: Add a streaming server like nginx-rtmp
  rtmp-server:
    image: tiangolo/nginx-rtmp
    container_name: rtmp-server
    restart: unless-stopped
    ports:
      - "1935:1935"  # RTMP
      - "8081:8080"  # HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hls:/tmp/hls
    
volumes:
  logs:
  hls: 