const CHARACTERS = [
    {
        name: 'Doge',
        hp: 120,
        maxMana: 100,
        baseAttack: 15,
        critical: 10,
        defend: 8,
        specialSkill1Cost: 30,
        specialSkill2Cost: 60,
        specialSkill1Name: 'Much Wow',
        specialSkill2Name: 'To The Moon',
        color: 0xFFD700,
        // Balanced tank character with good HP and decent attack
    },
    {
        name: 'Shiba',
        hp: 90,
        maxMana: 150,
        baseAttack: 18,
        critical: 20,
        defend: 5,
        specialSkill1Cost: 40,
        specialSkill2Cost: 80,
        specialSkill1Name: 'Shiba Slash',
        specialSkill2Name: 'Inu Impact',
        color: 0xA0522D,
        // High damage dealer with good critical chance
    },
    {
        name: 'Pepe',
        hp: 80,
        maxMana: 200,
        baseAttack: 22,
        critical: 25,
        defend: 3,
        specialSkill1Cost: 50,
        specialSkill2Cost: 100,
        specialSkill1Name: 'Rare Pepe',
        specialSkill2Name: 'Meme Magic',
        color: 0x90EE90,
        // Glass cannon - highest damage but very fragile
    },
    {
        name: 'SafeMoon',
        hp: 150,
        maxMana: 80,
        baseAttack: 12,
        critical: 5,
        defend: 15,
        specialSkill1Cost: 30,
        specialSkill2Cost: 60,
        specialSkill1Name: 'Safe Shield',
        specialSkill2Name: 'Lunar Launch',
        color: 0x4169E1,
        // Pure tank - highest HP and defense
    },
    {
        name: 'Floki',
        hp: 100,
        maxMana: 120,
        baseAttack: 16,
        critical: 15,
        defend: 10,
        specialSkill1Cost: 35,
        specialSkill2Cost: 70,
        specialSkill1Name: 'Viking Rage',
        specialSkill2Name: 'Norse Storm',
        color: 0xFF6B6B,
        // Well-rounded fighter with no weaknesses
    },
    {
        name: 'Akita',
        hp: 110,
        maxMana: 90,
        baseAttack: 20,
        critical: 8,
        defend: 12,
        specialSkill1Cost: 25,
        specialSkill2Cost: 50,
        specialSkill1Name: 'Akita Rush',
        specialSkill2Name: 'Pack Hunt',
        color: 0xFFA500,
        // High base damage with good survivability
    },
    {
        name: 'Bonk',
        hp: 70,
        maxMana: 180,
        baseAttack: 25,
        critical: 30,
        defend: 4,
        specialSkill1Cost: 45,
        specialSkill2Cost: 90,
        specialSkill1Name: 'Bonk Smash',
        specialSkill2Name: 'Cheems Power',
        color: 0xFF4500,
        // Extreme glass cannon - highest damage and crit, lowest HP
    },
    {
        name: 'Kishu',
        hp: 95,
        maxMana: 130,
        baseAttack: 17,
        critical: 18,
        defend: 7,
        specialSkill1Cost: 40,
        specialSkill2Cost: 75,
        specialSkill1Name: 'Kishu Blade',
        specialSkill2Name: 'Token Strike',
        color: 0x9370DB,
        // Balanced damage dealer with good mana pool
    }
]; 