const CHARACTERS = [
  {
    name: 'Doge',
    hp: 300,
    maxMana: 120,
    baseAttack: 12,
    critical: 15,
    defend: 10,
    specialSkill1Cost: 35,
    specialSkill2Cost: 70,
    specialSkill1Name: 'Much Wow',
    specialSkill2Name: 'To The Moon',
    color: 0xFFD700,
    // Balanced fighter with good survivability and decent special skills
  },
  {
    name: 'Shiba',
    hp: 280,
    maxMana: 140,
    baseAttack: 14,
    critical: 18,
    defend: 8,
    specialSkill1Cost: 40,
    specialSkill2Cost: 75,
    specialSkill1Name: 'Shiba Slash',
    specialSkill2Name: 'Inu Impact',
    color: 0xA0522D,
    // Aggressive fighter with high crit chance
  },
  {
    name: 'Pepe',
    hp: 260,
    maxMana: 160,
    baseAttack: 16,
    critical: 20,
    defend: 6,
    specialSkill1Cost: 45,
    specialSkill2Cost: 80,
    specialSkill1Name: 'Rare Pepe',
    specialSkill2Name: 'Meme Magic',
    color: 0x90EE90,
    // High risk, high reward fighter
  },
  {
    name: 'Mochi',
    hp: 320,
    maxMana: 100,
    baseAttack: 10,
    critical: 10,
    defend: 12,
    specialSkill1Cost: 30,
    specialSkill2Cost: 65,
    specialSkill1Name: 'Safe Shield',
    specialSkill2Name: 'Lunar Launch',
    color: 0x4169E1,
    // Tank with high HP and defense
  },
  {
    name: 'Floki',
    hp: 290,
    maxMana: 130,
    baseAttack: 13,
    critical: 16,
    defend: 9,
    specialSkill1Cost: 38,
    specialSkill2Cost: 72,
    specialSkill1Name: 'Viking Rage',
    specialSkill2Name: 'Norse Storm',
    color: 0xFF6B6B,
    // Well-rounded fighter with balanced stats
  },
  {
    name: 'Trump',
    hp: 295,
    maxMana: 110,
    baseAttack: 15,
    critical: 12,
    defend: 11,
    specialSkill1Cost: 35,
    specialSkill2Cost: 68,
    specialSkill1Name: 'Trump Rush',
    specialSkill2Name: 'Pack Hunt',
    color: 0xFFA500,
    // Offensive fighter with good defense
  },
  {
    name: 'Bonk',
    hp: 250,
    maxMana: 150,
    baseAttack: 18,
    critical: 22,
    defend: 5,
    specialSkill1Cost: 42,
    specialSkill2Cost: 78,
    specialSkill1Name: 'Bonk Smash',
    specialSkill2Name: 'Cheems Power',
    color: 0xFF4500,
    // Glass cannon with highest damage
  },
  {
    name: 'Kishu',
    hp: 285,
    maxMana: 135,
    baseAttack: 13,
    critical: 17,
    defend: 8,
    specialSkill1Cost: 38,
    specialSkill2Cost: 73,
    specialSkill1Name: 'Kishu Blade',
    specialSkill2Name: 'Token Strike',
    color: 0x9370DB,
    // Balanced fighter with good mana pool
  }
]; 
